{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X.X', GIT_DESCRIBE_NUMBER|int,   GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: yosys-uhdm
  version: {{ version }}

source:
  git_rev: {{ environ.get('UHDM_INTEGRATION_REV') }}
  git_url: https://github.com/alainmarcel/uhdm-integration.git

build:
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake
    - pkg-config
    - libuuid
    - gperftools
    - flex
    - libunwind
    - swig
  run:
    - ncurses

test:
  commands:
    - yosys-uhdm --version

