{% set version = '%s_%04i_%s'|format(PKG_TAG|replace('-','_'), PKG_NUMBER|int, PKG_GIT_HASH) %}
package:
  name: verible
  version: {{ version }}

source:
  git_url: https://github.com/google/verible

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - USE_SYSTEM_GCC_VERSION

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/google/verible
  license: Apache 2.0
  license_file: LICENSE
  summary: 'The main mission is to parse SystemVerilog (IEEE 1800-2017) for a wide variety of applications.'
