language: c

cache:
  ccache: true
  directories:
   - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/git_cache
   - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/src_cache
before_cache:
  - ./.travis/before_cache.sh

#dist: trusty
sudo: false
addons:
  apt:
    update: true
    packages:
    - realpath
    - autoconf
    - automake
    - build-essential
    - gperf
    - libftdi-dev
    - libudev-dev
    - libudev1
    - libusb-1.0-0-dev
    - libusb-dev
    - texinfo

before_install:
 - source $TRAVIS_BUILD_DIR/.travis/common.sh
 - bash $TRAVIS_BUILD_DIR/.travis/fixup-git.sh
 - source $TRAVIS_BUILD_DIR/.travis/common.sh

install:
 - ./.travis/install.sh

env:
  # riscv32 toolchain
  - PACKAGE=riscv32/binutils    CONDA_BUILD_VERSION=2.1.17
  # tools
  - PACKAGE=openocd             CONDA_BUILD_VERSION=2.1.17
  - PACKAGE=flterm              CONDA_BUILD_VERSION=2.1.17
  # verilog tools
  - PACKAGE=arachne-pnr
  - PACKAGE=icestorm
  - PACKAGE=iverilog
  - PACKAGE=verilator           CONDA_BUILD_VERSION=2.1.17
  - PACKAGE=vtr                 CONDA_CHANNELS=conda-forge
  - PACKAGE=yosys

script:
  - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_failure:
  - bash $TRAVIS_BUILD_DIR/.travis/after_failure.sh

after_success:
  - bash $TRAVIS_BUILD_DIR/.travis/after_success.sh
