{% set version = '%s_%04i_%s'|format(PKG_TAG, PKG_NUMBER|int, PKG_GIT_HASH) %}
package:
  name: surelog
  version: {{ version }}

source:
  git_url: https://github.com/alainmarcel/Surelog
  git_rev: master

build:
  number: {{ environ.get('DATE_NUM') }}
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config

  host:
    - python {{ python }}
    - gperftools
    - tk
    - libunwind
    - libuuid
    - swig

  run:
    - python

about:
  home: https://github.com/alainmarcel/Surelog
  license: Apache
  license_file: LICENSE
  summary: 'Parser/Compiler for SystemVerilog'
