{% set version = '%s_%04i_%s'|format(PKG_TAG, PKG_NUMBER|int, PKG_GIT_HASH) %}
package:
  name: sv-parser
  version: {{ version }}

source:
  git_url: https://github.com/dalance/sv-parser
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

test:
  commands:
    - parse_sv --version

about:
  home: https://github.com/dalance/sv-parser
  license: MIT
  license_file: LICENSE-MIT
  summary: SystemVerilog parser library fully complient with IEEE 1800-2017
